version: '3.9'

services:
  cinexplorer-api:
    image: postgres:12
    container_name: cinexplorer-api
    environment:
      POSTGRES_DB: cinexplorer-api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}